# Site settings
# Essas configurações são usadas para configurar o site como um todo.
# Você pode acessar essas configurações em qualquer lugar do site usando {{ site.title }} por exemplo.
# Você também pode criar suas próprias variáveis e usá-las em qualquer lugar do site.
# Exemplo: {{ site.myvariable }}

## Para usar localmente descomente as linhas abaixo
# baseurl: ""
# theme: minimal-mistakes-jekyll

## Para usar no github pages descomente as linhas abaixo e comente as linhas acima
baseurl: "c2dc-site"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

## Variáveis do site
# logo: /assets/images/perfil.png
title: Laborátório C2-DC
title_separator: "|"
subtitle: "Laboratory of Command and Control and Cyber-security"
name: "Lourenço Alves"
email: your-email@example.com
description: >- # Descrição em Multiplas linhas
  Laboratory of Command and Control and Cyber-security
url: "" # e.g. http://example.com
twitter_username: ""
github_username:  ""

minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

search: true
locale: "pt-BR"
# teaser: /assets/images/perfil.png
masthead_title: "C2-DC"
paginate: 3 # Numero de posts por página na home
paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      related: true
      toc: true
      author_profile: true

atom_feed:
  hide: true

author:
  name: "Fulano da Silva"
  avatar: "/assets/images/perfil.png"
  bio: "Professor do **ITA**" # Pode usar markdown
  location: "SJC-SP, Brasil"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
